name: Update PDF Preview

env:
  doc_name: VOTable

on:
  push:
    branches:
      - master

jobs:
  build:
    
    runs-on: ubuntu-latest
    
    steps:
    
    - name: Checkout the repository
      uses: actions/checkout@v1
      with:
        submodules: true
    
    - name: Setup dependencies
      run: |
        sudo add-apt-repository ppa:inkscape.dev/stable
        sudo apt update
        sudo apt install texlive-latex-base texlive-latex-recommended texlive-latex-extra texlive-fonts-recommended xsltproc latexmk ghostscript cm-super librsvg2-bin inkscape openjdk-8-jre-headless
        sudo snap install pdftk
    
    - name: Build the document
      run: |
        inkscape --version
        make
        make role_diagram.pdf biblio forcetex ${{ env.doc_name }}-draft.pdf
    
    - name: Check the output
      run: |
        test -f ${{ env.doc_name }}-draft.pdf
        test -f ${{ env.doc_name }}.bbl
    
    - name: Move the auto-pdf-preview tag
      uses: weareyipyip/walking-tag-action@v2
      with:
        tag-name: auto-pdf-preview
        tag-message: |
          Last commit taken into account for the automatically updated PDF preview of this IVOA document.
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Update the PDF preview
      uses: Xotl/cool-github-releases@v1
      with:
        mode: update
        isPrerelease: true
        tag_name: auto-pdf-preview
        release_name: "Auto PDF Preview"
        body_mrkdwn: |
          This release aims to provide a PDF preview of the last commit applied on this repository.
          It will be updated automatically after each merge of a PullRequest.
          **DO NOT PUBLISH THIS PRE-RELEASE!**"
          _Corresponding commit: ${{ github.sha }}_
        assets: ${{ env.doc_name }}-draft.pdf
        replace_assets: true
        github_token: ${{ secrets.GITHUB_TOKEN }}
